name: Generate and upload WinCC OA image  

on:
  push:
    branches: [ "main", "release/*", "develop", "develop/*" ]
#  pull_request:
#    branches: [ "main", "release/*", "develop", "develop/*" ]
  release:
    types: [published]

jobs:
  get_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          ENV_NAME=staging
          if [[ "${{ github.event_name }}" == "release" ]]; then
            ENV_NAME=staging
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ENV_NAME=staging
          else
            ENV_NAME=staging
          fi
          echo "::set-output name=env_name::${ENV_NAME}"
          
      - name: Chosen environment
        run: echo "Environment used ${{ steps.branch_check.outputs.env_name }}"
        
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}

  generate-winccoa-image:
    needs: [get_environment]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.get_environment.outputs.env_name }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Download current WinCC OA version
        env:
          ETM_USERNAME: ${{ secrets.ETM_USERNAME }}
          ETM_PASSWORD: ${{ secrets.ETM_PASSWORD }}
        run: scripts/download.sh

      - name: Unzip data
        run: |
          mkdir data && cd data && \
          unzip ../*.zip

      - name: Prepare data for Docker image build
        run: |
          # copy files provided from WinCC OA package for our custom Docker build
          cp data/docker-entrypoint.sh data/Dockerfile build-docker/
          # patch Dockerfile so it does not copy and install the packages, but only does preparation
          scripts/patchDockerfile.sh build-docker/Dockerfile

      - name: Docker build setup
        working-directory: ./build-docker
        run: |
          docker network create winccoarepo
          docker compose up -d
          # wait until repo data is generated
          docker compose wait create-repo

      - name: Docker build preparation image
        working-directory: ./build-docker
        run: |
          DOCKER_BUILDKIT=0 docker build --network=winccoarepo -t winccoaprepare:temp .

      - name: Docker build WinCC OA images
        working-directory: ./build-docker
        run: |
          DOCKER_BUILDKIT=0 docker build --network=winccoarepo -t winccoaprepare:temp .
          DOCKER_BUILDKIT=0 docker build --no-cache --network=winccoarepo --build-arg BASE_IMAGE=winccoaprepare:temp --target winccoaapi    --tag agruberetm/winccoa-3.19.7:api -f Dockerfile_install .
          DOCKER_BUILDKIT=0 docker build            --network=winccoarepo --build-arg BASE_IMAGE=winccoaprepare:temp --target winccoaserver --tag agruberetm/winccoa-3.19.7:baseserver -f Dockerfile_install .

      - name: Docker build teardown
        working-directory: ./build-docker
        run: |
          docker compose down
          docker network rm winccoarepo

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: |
          docker push agruberetm/winccoa-3.19.7:api
          docker push agruberetm/winccoa-3.19.7:baseserver
